### ISSUE TITLE
Better Earth texture

### ISSUE THREAD

**Issue by DeValdi** [Gnkgo/space-news#45]
The current Earth texture is rather low in quality and there are visual artifact issues when mipmapping (white lines).

If possible, we should find a texture where the edges of the icosahedron are slightly extended beyond their normal boundaries (a few pixels should suffice) to avoid such issues.

In addition, a higher resolution image allows for more accurate pin-pointing of location and fireball data.

**Comment by Nick20500** [comment]
The current earth texture file is a .bmp file. is this necessary or could the file type be diffrent?

**Comment by DeValdi** [comment]
> The current earth texture file is a .bmp file. is this necessary or could the file type be diffrent? @DeValdi

Can be a different format, though .jpeg might not work properly due to missing alpha channels.
If in doubt, we can easily convert any image to the .bmp format.
