### ISSUE TITLE
Tutorial clipping screen

### ISSUE THREAD

**Issue by DeValdi** [Gnkgo/space-news#62]
Tutorials were clipping the screen a while ago. No idea if they still do or if it has been fixed, just putting it out there. Feel free to close this if it has already been fixed.

**Comment by Nick20500** [comment]
The Homepage tutorial isn't clipping anymore. 
The spinning earth tutorial with the very long text was still clipping when I last saw it. 
I will adjust the spinning earth tutorial after it will be shortened.
